src/exec.cpp

Fixes the following bugs:
https://svn.boost.org/trac/boost/ticket/11100
https://svn.boost.org/trac/boost/ticket/8058

Fix #11100 and #8058: binary compatibility and leaked file handle in exec_file()

---

include/boost/python/exception_translator.hpp

This is a pull request for trac issue https://svn.boost.org/trac/boost/ticket/10932
I am compiling Boost.Python with `nvcc/6.5`, `gcc/4.6.2`, `python/2.7.8` and `cmake/3.0.1` right now.
As a side note, I modified the standard `FindPythonLibs.cmake` a bit to match the cuda_add_library calls.
During compile, get an error
```
boost/python/exception_translator.hpp(22): error: identifier "_1" is undefined
boost/python/exception_translator.hpp(22): error: identifier "_2" is undefined
```
due to a missing include:
```
#include <boost/bind/placeholders.hpp>
```

Fix Trac #10932 Missing Include: Bind Placeholders

---

src/exec.cpp

Backport commit 3e405b6fd5db5615bbef241763de070118222ca7 to develop branch: Fix exec_file for Python 3 < 3.4. Also fix version check to actually fix compilation with python 3.4.

Fix compilation with python 3.0-3.3

---

example/boost-build.jam
example/quickstart/boost-build.jam

Update examples to reflect this

Boost.Build now uses src/ instead of v2/

---

src/exec.cpp

A followup fix for the previous commit 36f8f6941134583cef0fa48701a1989f2f49d4ec.

Use _Py_fopen instead of fopen

---

include/boost/python/detail/msvc_typeinfo.hpp

The type_traits internal details used here are being moved to make it clear they are details and subject to change.  Old code will continue to work, but will warn about use of a deprecated header.

Stop Using type_traits details.

---

include/boost/python/detail/cv_category.hpp

This is the fix for https://svn.boost.org/trac/boost/ticket/10846.
@stefanseefeld, there you go. Rebased #12 on develop branch as requested.

Fix is_volatile constant in detail::cv_tag<>

---

example/quickstart/Jamroot

Uses of visual studio were getting a 'unresolved external symbol _mainCRTStartup' because there was no main() being linked into the test_embed.exe. I'm not a bjam expert, but I think that is because the embedding target is an executable (instead of an obj/lib?). I also have no idea if this was a problem on unix or if this fix will affect that platform.

Fixes empty example

---

doc/Jamfile

Not using '<format>html' as it seems it has to match the original
setting exactly.

Unset 'boost.defaults' set in Jamroot.

---

include/boost/python/data_members.hpp

This fixes the regression caused by 42e7d7b.
Fixes #39

Python: Fix condition for make_setter overload.

---

include/boost/python/detail/def_helper.hpp

The deprecated header is on type traits 'develop' branch.

Remove unused deprecated header file

---

include/boost/python/converter/registered.hpp

see http://stackoverflow.com/questions/12318693/c-segmentation-fault-
when-using-cout-in-static-variable-initialization for a reference of
what was happening when iostreams were used within boost.python
registry's global static ctors.

fix a static initialization fiasco with ios_base

---

include/boost/python/object/class_metadata.hpp

The conditional instantiation magic of maybe_register_pointer_to_python() assumes that use_value_holder and use_back_reference will be one of the boost::mpl::bool_ types, but this assumption is no longer true in Boost 1.60, where they can be standard library bool wrappers instead.
Explicitly defining these types as mpl::bool_ classes fixes https://github.com/boostorg/python/issues/56.

Fix auto-pointer registration in Boost Python 1.60.

---

include/boost/python/detail/wrap_python.hpp

This patch adds 64 bit support. 
Currently the lack of 64 bit support for Cygwin prevents projects from compiling on Cygwin64 (see Valloric/YouCompleteMe#684). Variations of this fix has been circulating for [a few years](https://github.com/Valloric/YouCompleteMe/issues/66#issuecomment-27879120).
Originally submitted [on the old Trac issue tracker 9 months ago](https://svn.boost.org/trac/boost/ticket/11125).

Add cygwin64 support to wrap_python.hpp

---

test/Jamfile.v2

This breaks the regression test suite

Add missing .py suffix

---

test/long.py
test/test_builtin_converters.py

Conditional import sys.version.major >= 3

Module 'past' is not available in 2.x interpreters

---

include/boost/python/signature.hpp

Avoid multiple template instances of boost::python::details::get_signature when multiple calling conventions are enabled

Multiple calling conventions with MSVC14/amd64

---

include/boost/python/slice.hpp

Because boost/detail/iterator.hpp is now obsoleted, see boostorg/iterator@b2b9ab156881e700858c5a104c47e006eddcc717 .

Fix a compile error with obsoleted details.

---

include/boost/python/object_core.hpp
include/boost/python/refcount.hpp

Due to programming errors, the reference count may already be zero before trying to decrement it. If nevertheless, the reference count is decremented, the PyObject will be left with a large reference count, pointing to already destroyed memory, possibly resulting in a hard-to-track segmentation fault. This fix introduces assertions that the reference count is above zero before decrementing it, which provide useful indications of this programming error in debug-builds (even when using a release-build of Python).
This [Gist](https://gist.github.com/WKarel/ff9eff5be792e0b4af2f4d12098a1bcb) shows how to produce a situation in which the assertions are helpful.

Assert refcount before decrement

---

test/test_builtin_converters.py

This was happening because the module docstring was not the first statement.

Fix a problem where test_builtin_converters.py is not being run

---

src/converter/builtin_converters.cpp
test/test_builtin_converters.py

On Windows, with Python >= 3.3, `PyObject_Length` cannot be used to get
the size of the `wchar_t` string, because it will count the number of
*code points*, but some characters not on the BMP will use two UTF-16
*code units* (surrogate pairs).
This is not a problem on Unix, since `wchar_t` is 32-bit.
This also fixes a problem where `test_builtin_converters.py` was not
being run, since the module docstring was not the first statement.

Fix conversion of PyUnicodeObject to wstring

---

include/boost/python/detail/config.hpp
include/boost/python/detail/exception_handler.hpp
include/boost/python/detail/wrapper_base.hpp
include/boost/python/errors.hpp
include/boost/python/object/instance.hpp

Found while cleaning up my git svn mirror after the conversion. The patch switches Boost.Python to the common BOOST_SYMBOL_\*  macros from Boost.Config. This includes some minor cleanups for gcc which does not like visibility attributes on forward declarations. Testest with gcc and msvc-9.0

Switch visibility support to  BOOST_SYMBOL_EXPORT. Refs #2114

---

build/Jamfile
include/boost/python/numpy.hpp
include/boost/python/numpy/config.hpp
include/boost/python/numpy/dtype.hpp
include/boost/python/numpy/matrix.hpp
include/boost/python/numpy/ndarray.hpp
include/boost/python/numpy/ufunc.hpp

Fix for missing export symbols in shared library of boost::python::numpy as reported and discussed in issue #98. Added config.hpp modified from python/detail/config.hpp for also numpy. Also added export declaration to functions/classes,

Fix for missing export symbols, issue #98

---

doc/reference/pickle.qbk

Due to changes on the python website, the url to the pickle library reference page was invalid.
Edit: Retrospectively all urls in the older boost docs don't work correctly.

Updated python library reference url for pickle

---

doc/tutorial.qbk
include/boost/python/exec.hpp
src/exec.cpp

Many times the caller may have a string created in C++,
so there is no need to wrap it in a Python object when
the only thing done with the object is extract<char*>.

exec/eval(): add overloads for char const*

---

include/boost/python/detail/dealloc.hpp
include/boost/python/opaque_pointer_converter.hpp
include/boost/python/return_opaque_pointer.hpp
test/crossmod_opaque.py
test/crossmod_opaque_a.cpp
test/crossmod_opaque_b.cpp
test/opaque.py

Nearly every header in the boost codebase is UTF-8, but here there
are a few headers which are using Windows-1252, which makes it impossible
for some tools to parse those files. This patch just reencodes them
with UTF-8 like the rest of the codebase. I checked that the name of the
author is still correct after this change.
No functional change intended.

Reencoded a few headers that used Windows-1252 with UTF-8.

---

include/boost/python/detail/config.hpp
include/boost/python/numpy/config.hpp

Fixes https://github.com/boostorg/python/issues/127
This was reusing the Python 2 name on Python 3, which is incorrect since the Python 3 library for Boost.Python now has a `3` in it. Hence this checks against the Python version and defines this correctly.

Fix `BOOST_LIB_NAME` for Python 3

---

include/boost/python/module_init.hpp

This was properly an oversight when switching to the BOOST_SYMBOL_*
symbols from Boost.Config in commit 0224f54a (see #1)
Since Boost.Config is already doing the differentiation between
different platforms and compilers we can simplify this bit and just
use BOOST_SYMBOL_EXPORT
This should fix #131

Fix symbol visibility of init method

---

include/boost/python/detail/caller.hpp

This fixes a small casting warning, and I believe is more correct. I however do not know if this is compatible with python < 2.7

Fix warning: returning the proper type for object sizes

---

src/object/enum.cpp

Unfortunately due to optimised build of Python3 libraries and executable I got only partial stack from [http://clang.llvm.org/docs/AddressSanitizer.html], however digging into and reducing my code I tracked it down to be issue with `boost/libs/python/src/object/enum.cpp`.
It has two bits that leak (and comment mentioning there is one):
PyObject *mod = PyObject_GetAttrString( self_, "__module__");
Leaks reference, as it never decreases it.
It also stores a new string object under object's `name` that ref count never gets decremented.
That commit fixes both issues.

Fix memory leaks in enum.cpp

---

config/cxx.py
include/boost/python/converter/registered.hpp
include/boost/python/converter/shared_ptr_to_python.hpp
include/boost/python/detail/is_shared_ptr.hpp
include/boost/python/detail/type_traits.hpp
include/boost/python/make_constructor.hpp
include/boost/python/object/class_metadata.hpp
include/boost/python/object/make_ptr_instance.hpp
include/boost/python/object/pointer_holder.hpp
include/boost/python/object/py_function.hpp
include/boost/python/to_python_indirect.hpp
include/boost/python/to_python_value.hpp

This fixes autoptr detection on VS2017.

Fix autoptr/unique_ptr ifdef for VS2017.

---

src/converter/builtin_converters.cpp

Python 3.7 changes the return type of _PyUnicode_AsString()
from void* to const char* -- causing the build of boost-python
to fail.
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>

Fix build with Python 3.7

---

src/numpy/numpy.cpp

This adds a missing return statement in the python3 specific
import logic of boost.python.numpy.
For python3 wrap_import_array() needs to return a pointer value.
The import_array() macro only returns NULL in case of error. The
missing return statement is UB, so the compiler can assume it does
not happen. This means the compiler can assume the error branch
is always taken, so import_array must always fail.
This fixes #214 and #209

Add missing return statement in numpy import

---

build/Jamfile

Since the previously added boost-install is in `if [ python.configured ]`, this `else` adds stage/install targets (that issue the preexisting warning message) in case Python hasn't been configured.

Add empty stage/install targets when Python is not configured

---

src/object/function.cpp

Python 3.7.0 asserts that attribute lookup functions are called without outstanding exceptions:
https://github.com/python/cpython/blob/v3.7.0a2/Objects/typeobject.c#L3037
Motivation: https://bugs.python.org/issue34068#msg321262
Therefore the error set by the first PyObject_GetItem should be cleared before calling PyObject_GetAttrString.

clear python exception after expected attribute lookup failure

---

include/boost/python/detail/wrap_python.hpp

Suppresses the warning on GCC, Clang, and MSVC.
Probably it is worth cherry-picking into the master as even the release managers had the trouble with Python 2 headers.
Playground: https://godbolt.org/z/ioqTlS

Fix -Wregister error on Clang in C++17 mode

---

doc/tutorial.qbk

I think it's meant to refer to the Jamroot file being discussed, not Jamrules.

Fix name of file in tutorial

---

include/boost/python/detail/unwind_type.hpp

Name lookup in msvc has changed between 14.14 and 14.15 making it consistent with other compilers. Forward declaration of unwind_type() is now required as it is for other compilers.
Resolves compilation errors identified in:
https://github.com/boostorg/python/issues/228

Enable forward declaration of unwind_type() in msvc14.15 and later.

---

test/test_class.hpp

Since recently lightweight_test introduced a sanitation to ensure that `boost::report_errors()` is called, and it does not in module tests.
The problem could be fixed by exporting the function and calling it from these python tests, but as it already done in other module tests I just turned those usages lightweight_test to a regular assertation.
ref #254

Fixed module tests fail

---

build/Jamfile

The library `boost_numpy` is conditioned on `[ python.numpy ]`, so only `boost-install` it when this condition holds.
This also moves the libraries outside `if [ python.configured ]` (as was the case before) since they are already guarded with `[ cond ]`.

Only boost-install boost_numpy when it's being built

---

include/boost/python/object/iterator.hpp

The header is deprecated in favor of `<iterator>`. It generates compiler warnings and will be removed in a future release.

Remove usage of deprecated header boost/detail/iterator.hpp

---

test/args.py
test/dict.cpp
test/dict.py
test/fabscript
test/iterator.py
test/list.py
test/long.py
test/map_indexing_suite.py
test/object.py
test/pickle2.py
test/pickle3.py
test/str.py
test/test_builtin_converters.py
test/tuple.py

905b34210b9ae2310c61b52584313e33b7f131ca added Python 3 compatibility for the tests. However, due to the behavior of doctest, this silently disabled some of the tests. For doctest to pick up module docstrings, the docstring has to be the first statement of the module. You can see that the tests are failing to execute if you add `verbose=True` to the `doctest.testmod()` call.
This PR fixes this error for all 12 modules where there was a non-docstring as the first statement, and then adds minor fixups to the tests to make sure they execute on both Python 2 and Python 3.

Ensure all doctests run

---

include/boost/python/long.hpp
src/long.cpp

PyLong_Type raises an exception if the argument is not convertible to
long, therefore, this has to be handled as new_reference and not
new_non_null_reference, otherwise a segfault will occur.

Handle NULL from call to PyLong_Type

---

.travis.yml
src/exec.cpp
src/wrapper.cpp

Resolves https://svn.boost.org/trac10/ticket/4125
This change uses the official python macros for object access.  This should have no impact on existing CPython usage, but will permit alternate pythons (such as pypy) to utilize boost.

Use python macros to permit alternate pythons (start pypy)

---

.appveyor.yml

Version number needed to be manually rolled to match what is installed in appveyor.

New VS2019 version on appveyor

---

src/exec.cpp

Replace private _Py_fopen() with public fopen(): private _Py_fopen()
function was removed in 3.10.0a4:
https://bugs.python.org/issue32381

Fix compatibility with Python 3.10.0a4: fopen

---

build/Jamfile

This fixes issue #361 by using the `/python//numpy` target. It however requires the corresponding Boost.Build PR https://github.com/boostorg/build/pull/726 to be merged first.

Use the /python//numpy target instead of [ numpy.include ] (fixes #361)

---

include/boost/python/exception_translator.hpp
include/boost/python/iterator.hpp
src/object/function.cpp
src/object/inheritance.cpp
src/object/iterator.cpp
test/import_.cpp

Using `<boost/bind.hpp>` without `BOOST_BIND_GLOBAL_PLACEHOLDERS` is deprecated.
This patch replaces the usage of `<boost/bind.hpp>` with `<boost/bind/bind.hpp>` and inserts 
`using namespace boost::placeholders` when necessary.

Fix deprecated usage of <boost/bind.hpp>

---

include/boost/python/call_method.hpp

Was missing from https://github.com/boostorg/python/pull/320
I've tested it on one of my projects with (that patch on) Boost.Python/Boost 1.76.0 and it works well. Without that patch, there is a deprecation error.

Update call_method.hpp to avoid deprecation issue on PyEval

---

src/object/enum.cpp

The enum_type_object type inherits from PyLong_Type which is not tracked
by the GC. Instances doesn't have to be tracked by the GC: remove the
Py_TPFLAGS_HAVE_GC flag.
The Python C API documentation says:
"To create a container type, the tp_flags field of the type object
must include the Py_TPFLAGS_HAVE_GC and provide an implementation of
the tp_traverse handler."
https://docs.python.org/dev/c-api/gcsupport.html
The new exception was introduced in Python 3.11 by:
https://github.com/python/cpython/issues/88429

Fix enum_type_object type on Python 3.11

---

include/boost/python/detail/config.hpp

The static/dynamic config macro logic had two issues; first, it used unconventional macro names (BOOST_PYTHON_STATIC_LIB and BOOST_PYTHON_DYNAMIC_LIB instead of BOOST_PYTHON_STATIC_LINK and BOOST_PYTHON_DYNAMIC_LINK as everything else); second, when both BOOST_PYTHON_STATIC_LINK and BOOST_PYTHON_STATIC_LIB were defined, it caused a macro redefinition warning.
This change fixes both.

Normalize static/dynamic link macros and avoid redefinition warnings

---

src/numpy/dtype.cpp

Compare pointers directly instead of using PyArray_EquivTypes
Fixes #376

Another fix for numpy 2.0

---

build.jam
build/Jamfile
example/README.md
test/Jamfile

This is part of the effort to make the Boost libraries "modular" for build and consumption. See https://lists.boost.org/Archives/boost/2024/01/255704.php and https://github.com/grafikrobot/boost-b2-modular/blob/b2-modular/README.adoc for more information.
This PR depends on the following other PRs being merged to both develop and master branches of the respective repos:
- https://github.com/boostorg/boost/pull/854
This PR will be changed to ready for review, i.e. not draft, when the above are merged. Do not merge this one until that time.

Add support for modular build structure.

---

include/boost/python/make_constructor.hpp
src/object/class.cpp

Fixed a crash on Solaris 11 with gcc 7.3.1 when a binding uses make_constructor () like:
```cpp
def_class<integer_type> ("numeric")
.def("__init__", make_constructor (&integer::from_tuple),
"Initialize from a tuple")
```
The crash is caused from pull request #360. It works fine when I revert the changes of this pull request.
In make_constructor.hpp, the address of the structure pointer_holder should be aligned with the correct alignment value instead of the default value 1. Otherwise, it crashes in the placement new operator:
```cpp
(new (memory) holder(std::move(x)))
```
Fix the calculation of the padding required to align the start of a data structure. The padding cannot be equal to the alignment. It is always smaller than the alignment. The formula is taken from wikipedia which is …

Alignment fixes

---

src/object/class.cpp

Call to the destructor ends lifetime of the object, including vptr
used by dynamic_cast.

dynamic_cast before destructor

---

doc/numpy/_static/boost.css
doc/numpy/_templates/layout.html

Hi,
The current boostorg/boost bundle has been created using Sphinx version 1.5.6 
If upgrading _all_ packages and Sphinx changes to 5.2.1, the numpy docs are slightly broken. 
- Search doesn't work  
- bullet lists are widely spaced   
Researched the problems in https://github.com/sphinx-doc/sphinx/issues . After some experimentation it looks like the fix in this pull request solves the issues.

Support newer version of Sphinx

---

include/boost/python/object_operators.hpp

`boost/iterator/detail/enable_if.hpp` has been deleted. Replace with `boost/type_traits/enable_if.hpp`.

Replace use of boost/iterator/detail/enable_if.hpp
